apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: sajin-moa
  namespace: argocd

spec:
  description: sajin-moa applications

  sourceRepos:
    - https://github.com/nhs0912/moa-gitops.git

  destinations:
    - namespace: sajin-moa-dev
      server: https://kubernetes.default.svc

    - namespace: sajin-moa-stg
      server: https://kubernetes.default.svc

    - namespace: sajin-moa-prod
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: ''
      kind: Namespace

  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
