apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sajin-moa-dev

resources:
- ../../base
- namespace.yaml
- ingress.yaml

patches:
- path: backend-patch.yaml
- path: frontend-patch.yaml
- path: configmap-patch.yaml


images:
- name: docker.io/nhs0912/moa-back
- name: docker.io/nhs0912/moa-backend
  newName: docker.io/nhs0912/sajin-moa-backend
  newTag: dev-1d07de0
- name: docker.io/nhs0912/moa-frontend
  newName: docker.io/nhs0912/sajin-moa-frontend
  newTag: dev-8d43764
- name: docker.io/nhs0912/sajin-moa-back
  newTag: 03538b8
- name: docker.io/nhs0912/sajin-moa-frontend
  newName: docker.io/nhs0912/sajin-moa-frontend
  newTag: dev-694c208
