apiVersion: v1
kind: Secret
metadata:
  name: sajin-moa-redis-secret
  labels:
    app.kubernetes.io/name: sajin-moa-redis
    app.kubernetes.io/component: redis
    app.kubernetes.io/part-of: sajin-moa

type: Opaque

stringData:
  redis-password: "#Redis0912"