apiVersion: v1
kind: Service
metadata:
  name: sajin-moa-redis
  labels:
    app.kubernetes.io/name: sajin-moa-redis
    app.kubernetes.io/component: redis
    app.kubernetes.io/part-of: sajin-moa

spec:
  type: ClusterIP

  selector:
    app.kubernetes.io/name: sajin-moa-redis

  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: redis