apiVersion: v1
kind: Service
metadata:
  name: sajin-moa-back
  labels:
    app.kubernetes.io/name: sajin-moa-back
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: sajin-moa

spec:
  type: ClusterIP

  selector:
    app.kubernetes.io/name: sajin-moa-back

  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP


