apiVersion: v1
kind: Service
metadata:
  name: sajin-moa-frontend
  labels:
    app.kubernetes.io/name: sajin-moa-frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: sajin-moa

spec:
  type: ClusterIP

  selector:
    app.kubernetes.io/name: sajin-moa-frontend

  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP